//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancieraMobile.RestService.ServicioBanca {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioType", Namespace="http://financiera.dsd.net/banca/")]
    [System.SerializableAttribute()]
    public partial class UsuarioType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int usuarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int usuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                if ((this.usuarioIdField.Equals(value) != true)) {
                    this.usuarioIdField = value;
                    this.RaisePropertyChanged("usuarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BancoType", Namespace="http://financiera.dsd.net/banca/")]
    [System.SerializableAttribute()]
    public partial class BancoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int bancoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int bancoId {
            get {
                return this.bancoIdField;
            }
            set {
                if ((this.bancoIdField.Equals(value) != true)) {
                    this.bancoIdField = value;
                    this.RaisePropertyChanged("bancoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaType", Namespace="http://financiera.dsd.net/banca/")]
    [System.SerializableAttribute()]
    public partial class CuentaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int cuentaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int cuentaId {
            get {
                return this.cuentaIdField;
            }
            set {
                if ((this.cuentaIdField.Equals(value) != true)) {
                    this.cuentaIdField = value;
                    this.RaisePropertyChanged("cuentaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroField, value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://financiera.dsd.net/banca/", ConfigurationName="ServicioBanca.ServicioBancaSoap")]
    public interface ServicioBancaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento codigo del espacio de nombres http://financiera.dsd.net/banca/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://financiera.dsd.net/banca/autenticar", ReplyAction="*")]
        FinancieraMobile.RestService.ServicioBanca.autenticarResponse autenticar(FinancieraMobile.RestService.ServicioBanca.autenticarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://financiera.dsd.net/banca/autenticar", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioBanca.autenticarResponse> autenticarAsync(FinancieraMobile.RestService.ServicioBanca.autenticarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento listarBancosPorUsuarioResult del espacio de nombres http://financiera.dsd.net/banca/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://financiera.dsd.net/banca/listarBancosPorUsuario", ReplyAction="*")]
        FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioResponse listarBancosPorUsuario(FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://financiera.dsd.net/banca/listarBancosPorUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioResponse> listarBancosPorUsuarioAsync(FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento listarCuentasPorUsuarioBancoResult del espacio de nombres http://financiera.dsd.net/banca/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://financiera.dsd.net/banca/listarCuentasPorUsuarioBanco", ReplyAction="*")]
        FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoResponse listarCuentasPorUsuarioBanco(FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://financiera.dsd.net/banca/listarCuentasPorUsuarioBanco", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoResponse> listarCuentasPorUsuarioBancoAsync(FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autenticarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autenticar", Namespace="http://financiera.dsd.net/banca/", Order=0)]
        public FinancieraMobile.RestService.ServicioBanca.autenticarRequestBody Body;
        
        public autenticarRequest() {
        }
        
        public autenticarRequest(FinancieraMobile.RestService.ServicioBanca.autenticarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://financiera.dsd.net/banca/")]
    public partial class autenticarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string claveweb;
        
        public autenticarRequestBody() {
        }
        
        public autenticarRequestBody(string codigo, string claveweb) {
            this.codigo = codigo;
            this.claveweb = claveweb;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autenticarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autenticarResponse", Namespace="http://financiera.dsd.net/banca/", Order=0)]
        public FinancieraMobile.RestService.ServicioBanca.autenticarResponseBody Body;
        
        public autenticarResponse() {
        }
        
        public autenticarResponse(FinancieraMobile.RestService.ServicioBanca.autenticarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://financiera.dsd.net/banca/")]
    public partial class autenticarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public FinancieraMobile.RestService.ServicioBanca.UsuarioType usuario;
        
        public autenticarResponseBody() {
        }
        
        public autenticarResponseBody(FinancieraMobile.RestService.ServicioBanca.UsuarioType usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarBancosPorUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarBancosPorUsuario", Namespace="http://financiera.dsd.net/banca/", Order=0)]
        public FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioRequestBody Body;
        
        public listarBancosPorUsuarioRequest() {
        }
        
        public listarBancosPorUsuarioRequest(FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://financiera.dsd.net/banca/")]
    public partial class listarBancosPorUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int usuarioId;
        
        public listarBancosPorUsuarioRequestBody() {
        }
        
        public listarBancosPorUsuarioRequestBody(int usuarioId) {
            this.usuarioId = usuarioId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarBancosPorUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarBancosPorUsuarioResponse", Namespace="http://financiera.dsd.net/banca/", Order=0)]
        public FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioResponseBody Body;
        
        public listarBancosPorUsuarioResponse() {
        }
        
        public listarBancosPorUsuarioResponse(FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://financiera.dsd.net/banca/")]
    public partial class listarBancosPorUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FinancieraMobile.RestService.ServicioBanca.BancoType[] listarBancosPorUsuarioResult;
        
        public listarBancosPorUsuarioResponseBody() {
        }
        
        public listarBancosPorUsuarioResponseBody(FinancieraMobile.RestService.ServicioBanca.BancoType[] listarBancosPorUsuarioResult) {
            this.listarBancosPorUsuarioResult = listarBancosPorUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarCuentasPorUsuarioBancoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarCuentasPorUsuarioBanco", Namespace="http://financiera.dsd.net/banca/", Order=0)]
        public FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoRequestBody Body;
        
        public listarCuentasPorUsuarioBancoRequest() {
        }
        
        public listarCuentasPorUsuarioBancoRequest(FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://financiera.dsd.net/banca/")]
    public partial class listarCuentasPorUsuarioBancoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int usuarioId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int bancoId;
        
        public listarCuentasPorUsuarioBancoRequestBody() {
        }
        
        public listarCuentasPorUsuarioBancoRequestBody(int usuarioId, int bancoId) {
            this.usuarioId = usuarioId;
            this.bancoId = bancoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarCuentasPorUsuarioBancoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarCuentasPorUsuarioBancoResponse", Namespace="http://financiera.dsd.net/banca/", Order=0)]
        public FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoResponseBody Body;
        
        public listarCuentasPorUsuarioBancoResponse() {
        }
        
        public listarCuentasPorUsuarioBancoResponse(FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://financiera.dsd.net/banca/")]
    public partial class listarCuentasPorUsuarioBancoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FinancieraMobile.RestService.ServicioBanca.CuentaType[] listarCuentasPorUsuarioBancoResult;
        
        public listarCuentasPorUsuarioBancoResponseBody() {
        }
        
        public listarCuentasPorUsuarioBancoResponseBody(FinancieraMobile.RestService.ServicioBanca.CuentaType[] listarCuentasPorUsuarioBancoResult) {
            this.listarCuentasPorUsuarioBancoResult = listarCuentasPorUsuarioBancoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioBancaSoapChannel : FinancieraMobile.RestService.ServicioBanca.ServicioBancaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioBancaSoapClient : System.ServiceModel.ClientBase<FinancieraMobile.RestService.ServicioBanca.ServicioBancaSoap>, FinancieraMobile.RestService.ServicioBanca.ServicioBancaSoap {
        
        public ServicioBancaSoapClient() {
        }
        
        public ServicioBancaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioBancaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioBancaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioBancaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancieraMobile.RestService.ServicioBanca.autenticarResponse FinancieraMobile.RestService.ServicioBanca.ServicioBancaSoap.autenticar(FinancieraMobile.RestService.ServicioBanca.autenticarRequest request) {
            return base.Channel.autenticar(request);
        }
        
        public FinancieraMobile.RestService.ServicioBanca.UsuarioType autenticar(string codigo, string claveweb) {
            FinancieraMobile.RestService.ServicioBanca.autenticarRequest inValue = new FinancieraMobile.RestService.ServicioBanca.autenticarRequest();
            inValue.Body = new FinancieraMobile.RestService.ServicioBanca.autenticarRequestBody();
            inValue.Body.codigo = codigo;
            inValue.Body.claveweb = claveweb;
            FinancieraMobile.RestService.ServicioBanca.autenticarResponse retVal = ((FinancieraMobile.RestService.ServicioBanca.ServicioBancaSoap)(this)).autenticar(inValue);
            return retVal.Body.usuario;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioBanca.autenticarResponse> FinancieraMobile.RestService.ServicioBanca.ServicioBancaSoap.autenticarAsync(FinancieraMobile.RestService.ServicioBanca.autenticarRequest request) {
            return base.Channel.autenticarAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioBanca.autenticarResponse> autenticarAsync(string codigo, string claveweb) {
            FinancieraMobile.RestService.ServicioBanca.autenticarRequest inValue = new FinancieraMobile.RestService.ServicioBanca.autenticarRequest();
            inValue.Body = new FinancieraMobile.RestService.ServicioBanca.autenticarRequestBody();
            inValue.Body.codigo = codigo;
            inValue.Body.claveweb = claveweb;
            return ((FinancieraMobile.RestService.ServicioBanca.ServicioBancaSoap)(this)).autenticarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioResponse FinancieraMobile.RestService.ServicioBanca.ServicioBancaSoap.listarBancosPorUsuario(FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioRequest request) {
            return base.Channel.listarBancosPorUsuario(request);
        }
        
        public FinancieraMobile.RestService.ServicioBanca.BancoType[] listarBancosPorUsuario(int usuarioId) {
            FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioRequest inValue = new FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioRequest();
            inValue.Body = new FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioRequestBody();
            inValue.Body.usuarioId = usuarioId;
            FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioResponse retVal = ((FinancieraMobile.RestService.ServicioBanca.ServicioBancaSoap)(this)).listarBancosPorUsuario(inValue);
            return retVal.Body.listarBancosPorUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioResponse> FinancieraMobile.RestService.ServicioBanca.ServicioBancaSoap.listarBancosPorUsuarioAsync(FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioRequest request) {
            return base.Channel.listarBancosPorUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioResponse> listarBancosPorUsuarioAsync(int usuarioId) {
            FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioRequest inValue = new FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioRequest();
            inValue.Body = new FinancieraMobile.RestService.ServicioBanca.listarBancosPorUsuarioRequestBody();
            inValue.Body.usuarioId = usuarioId;
            return ((FinancieraMobile.RestService.ServicioBanca.ServicioBancaSoap)(this)).listarBancosPorUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoResponse FinancieraMobile.RestService.ServicioBanca.ServicioBancaSoap.listarCuentasPorUsuarioBanco(FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoRequest request) {
            return base.Channel.listarCuentasPorUsuarioBanco(request);
        }
        
        public FinancieraMobile.RestService.ServicioBanca.CuentaType[] listarCuentasPorUsuarioBanco(int usuarioId, int bancoId) {
            FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoRequest inValue = new FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoRequest();
            inValue.Body = new FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoRequestBody();
            inValue.Body.usuarioId = usuarioId;
            inValue.Body.bancoId = bancoId;
            FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoResponse retVal = ((FinancieraMobile.RestService.ServicioBanca.ServicioBancaSoap)(this)).listarCuentasPorUsuarioBanco(inValue);
            return retVal.Body.listarCuentasPorUsuarioBancoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoResponse> FinancieraMobile.RestService.ServicioBanca.ServicioBancaSoap.listarCuentasPorUsuarioBancoAsync(FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoRequest request) {
            return base.Channel.listarCuentasPorUsuarioBancoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoResponse> listarCuentasPorUsuarioBancoAsync(int usuarioId, int bancoId) {
            FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoRequest inValue = new FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoRequest();
            inValue.Body = new FinancieraMobile.RestService.ServicioBanca.listarCuentasPorUsuarioBancoRequestBody();
            inValue.Body.usuarioId = usuarioId;
            inValue.Body.bancoId = bancoId;
            return ((FinancieraMobile.RestService.ServicioBanca.ServicioBancaSoap)(this)).listarCuentasPorUsuarioBancoAsync(inValue);
        }
    }
}
