//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancieraMobile.RestService.ServicioCda {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CdaType", Namespace="http://financiera.dsd.net/cda/")]
    [System.SerializableAttribute()]
    public partial class CdaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cdaField;
        
        private double montoPagoField;
        
        private System.DateTime fechaGeneracionField;
        
        private System.DateTime fechaPagoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cda {
            get {
                return this.cdaField;
            }
            set {
                if ((object.ReferenceEquals(this.cdaField, value) != true)) {
                    this.cdaField = value;
                    this.RaisePropertyChanged("cda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double montoPago {
            get {
                return this.montoPagoField;
            }
            set {
                if ((this.montoPagoField.Equals(value) != true)) {
                    this.montoPagoField = value;
                    this.RaisePropertyChanged("montoPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime fechaGeneracion {
            get {
                return this.fechaGeneracionField;
            }
            set {
                if ((this.fechaGeneracionField.Equals(value) != true)) {
                    this.fechaGeneracionField = value;
                    this.RaisePropertyChanged("fechaGeneracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime fechaPago {
            get {
                return this.fechaPagoField;
            }
            set {
                if ((this.fechaPagoField.Equals(value) != true)) {
                    this.fechaPagoField = value;
                    this.RaisePropertyChanged("fechaPago");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://financiera.dsd.net/cda/", ConfigurationName="ServicioCda.ServicioCdaSoap")]
    public interface ServicioCdaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (GenerarCda) del mensaje GenerarCda no coincide con el valor predeterminado (generarCda)
        [System.ServiceModel.OperationContractAttribute(Action="http://financiera.dsd.net/cda/GenerarCda", ReplyAction="*")]
        FinancieraMobile.RestService.ServicioCda.GenerarCda1 generarCda(FinancieraMobile.RestService.ServicioCda.GenerarCda request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://financiera.dsd.net/cda/GenerarCda", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioCda.GenerarCda1> generarCdaAsync(FinancieraMobile.RestService.ServicioCda.GenerarCda request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://financiera.dsd.net/cda/PagarCda", ReplyAction="*")]
        FinancieraMobile.RestService.ServicioCda.PagarCda1 pagarCda(FinancieraMobile.RestService.ServicioCda.PagarCda request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://financiera.dsd.net/cda/PagarCda", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioCda.PagarCda1> pagarCdaAsync(FinancieraMobile.RestService.ServicioCda.PagarCda request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ListarCda) del mensaje ListarCda no coincide con el valor predeterminado (listarCda)
        [System.ServiceModel.OperationContractAttribute(Action="http://financiera.dsd.net/cda/ListarCda", ReplyAction="*")]
        FinancieraMobile.RestService.ServicioCda.ListarCda1 listarCda(FinancieraMobile.RestService.ServicioCda.ListarCda request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://financiera.dsd.net/cda/ListarCda", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioCda.ListarCda1> listarCdaAsync(FinancieraMobile.RestService.ServicioCda.ListarCda request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://financiera.dsd.net/cda/ConsultarCda", ReplyAction="*")]
        FinancieraMobile.RestService.ServicioCda.ConsultarCda1 consultarCda(FinancieraMobile.RestService.ServicioCda.ConsultarCda request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://financiera.dsd.net/cda/ConsultarCda", ReplyAction="*")]
        System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioCda.ConsultarCda1> consultarCdaAsync(FinancieraMobile.RestService.ServicioCda.ConsultarCda request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerarCda", WrapperNamespace="http://financiera.dsd.net/cda/", IsWrapped=true)]
    public partial class GenerarCda {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://financiera.dsd.net/cda/", Order=0)]
        public double montopago;
        
        public GenerarCda() {
        }
        
        public GenerarCda(double montopago) {
            this.montopago = montopago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerarCdaResponse", WrapperNamespace="http://financiera.dsd.net/cda/", IsWrapped=true)]
    public partial class GenerarCda1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://financiera.dsd.net/cda/", Order=0)]
        public FinancieraMobile.RestService.ServicioCda.CdaType cda;
        
        public GenerarCda1() {
        }
        
        public GenerarCda1(FinancieraMobile.RestService.ServicioCda.CdaType cda) {
            this.cda = cda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarCda {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagarCda", Namespace="http://financiera.dsd.net/cda/", Order=0)]
        public FinancieraMobile.RestService.ServicioCda.PagarCdaBody Body;
        
        public PagarCda() {
        }
        
        public PagarCda(FinancieraMobile.RestService.ServicioCda.PagarCdaBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://financiera.dsd.net/cda/")]
    public partial class PagarCdaBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cda;
        
        public PagarCdaBody() {
        }
        
        public PagarCdaBody(string cda) {
            this.cda = cda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarCda1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagarCdaResponse", Namespace="http://financiera.dsd.net/cda/", Order=0)]
        public FinancieraMobile.RestService.ServicioCda.PagarCda1Body Body;
        
        public PagarCda1() {
        }
        
        public PagarCda1(FinancieraMobile.RestService.ServicioCda.PagarCda1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://financiera.dsd.net/cda/")]
    public partial class PagarCda1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public FinancieraMobile.RestService.ServicioCda.CdaType cda;
        
        public PagarCda1Body() {
        }
        
        public PagarCda1Body(FinancieraMobile.RestService.ServicioCda.CdaType cda) {
            this.cda = cda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarCda", WrapperNamespace="http://financiera.dsd.net/cda/", IsWrapped=true)]
    public partial class ListarCda {
        
        public ListarCda() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarCdaResponse", WrapperNamespace="http://financiera.dsd.net/cda/", IsWrapped=true)]
    public partial class ListarCda1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://financiera.dsd.net/cda/", Order=0)]
        public FinancieraMobile.RestService.ServicioCda.CdaType[] ListarCdaResult;
        
        public ListarCda1() {
        }
        
        public ListarCda1(FinancieraMobile.RestService.ServicioCda.CdaType[] ListarCdaResult) {
            this.ListarCdaResult = ListarCdaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarCda {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarCda", Namespace="http://financiera.dsd.net/cda/", Order=0)]
        public FinancieraMobile.RestService.ServicioCda.ConsultarCdaBody Body;
        
        public ConsultarCda() {
        }
        
        public ConsultarCda(FinancieraMobile.RestService.ServicioCda.ConsultarCdaBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://financiera.dsd.net/cda/")]
    public partial class ConsultarCdaBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cda;
        
        public ConsultarCdaBody() {
        }
        
        public ConsultarCdaBody(string cda) {
            this.cda = cda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarCda1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarCdaResponse", Namespace="http://financiera.dsd.net/cda/", Order=0)]
        public FinancieraMobile.RestService.ServicioCda.ConsultarCda1Body Body;
        
        public ConsultarCda1() {
        }
        
        public ConsultarCda1(FinancieraMobile.RestService.ServicioCda.ConsultarCda1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://financiera.dsd.net/cda/")]
    public partial class ConsultarCda1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public FinancieraMobile.RestService.ServicioCda.CdaType cda;
        
        public ConsultarCda1Body() {
        }
        
        public ConsultarCda1Body(FinancieraMobile.RestService.ServicioCda.CdaType cda) {
            this.cda = cda;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioCdaSoapChannel : FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCdaSoapClient : System.ServiceModel.ClientBase<FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap>, FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap {
        
        public ServicioCdaSoapClient() {
        }
        
        public ServicioCdaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCdaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCdaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCdaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancieraMobile.RestService.ServicioCda.GenerarCda1 FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap.generarCda(FinancieraMobile.RestService.ServicioCda.GenerarCda request) {
            return base.Channel.generarCda(request);
        }
        
        public FinancieraMobile.RestService.ServicioCda.CdaType generarCda(double montopago) {
            FinancieraMobile.RestService.ServicioCda.GenerarCda inValue = new FinancieraMobile.RestService.ServicioCda.GenerarCda();
            inValue.montopago = montopago;
            FinancieraMobile.RestService.ServicioCda.GenerarCda1 retVal = ((FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap)(this)).generarCda(inValue);
            return retVal.cda;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioCda.GenerarCda1> FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap.generarCdaAsync(FinancieraMobile.RestService.ServicioCda.GenerarCda request) {
            return base.Channel.generarCdaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioCda.GenerarCda1> generarCdaAsync(double montopago) {
            FinancieraMobile.RestService.ServicioCda.GenerarCda inValue = new FinancieraMobile.RestService.ServicioCda.GenerarCda();
            inValue.montopago = montopago;
            return ((FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap)(this)).generarCdaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancieraMobile.RestService.ServicioCda.PagarCda1 FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap.pagarCda(FinancieraMobile.RestService.ServicioCda.PagarCda request) {
            return base.Channel.pagarCda(request);
        }
        
        public FinancieraMobile.RestService.ServicioCda.CdaType pagarCda(string cda) {
            FinancieraMobile.RestService.ServicioCda.PagarCda inValue = new FinancieraMobile.RestService.ServicioCda.PagarCda();
            inValue.Body = new FinancieraMobile.RestService.ServicioCda.PagarCdaBody();
            inValue.Body.cda = cda;
            FinancieraMobile.RestService.ServicioCda.PagarCda1 retVal = ((FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap)(this)).pagarCda(inValue);
            return retVal.Body.cda;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioCda.PagarCda1> FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap.pagarCdaAsync(FinancieraMobile.RestService.ServicioCda.PagarCda request) {
            return base.Channel.pagarCdaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioCda.PagarCda1> pagarCdaAsync(string cda) {
            FinancieraMobile.RestService.ServicioCda.PagarCda inValue = new FinancieraMobile.RestService.ServicioCda.PagarCda();
            inValue.Body = new FinancieraMobile.RestService.ServicioCda.PagarCdaBody();
            inValue.Body.cda = cda;
            return ((FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap)(this)).pagarCdaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancieraMobile.RestService.ServicioCda.ListarCda1 FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap.listarCda(FinancieraMobile.RestService.ServicioCda.ListarCda request) {
            return base.Channel.listarCda(request);
        }
        
        public FinancieraMobile.RestService.ServicioCda.CdaType[] listarCda() {
            FinancieraMobile.RestService.ServicioCda.ListarCda inValue = new FinancieraMobile.RestService.ServicioCda.ListarCda();
            FinancieraMobile.RestService.ServicioCda.ListarCda1 retVal = ((FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap)(this)).listarCda(inValue);
            return retVal.ListarCdaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioCda.ListarCda1> FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap.listarCdaAsync(FinancieraMobile.RestService.ServicioCda.ListarCda request) {
            return base.Channel.listarCdaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioCda.ListarCda1> listarCdaAsync() {
            FinancieraMobile.RestService.ServicioCda.ListarCda inValue = new FinancieraMobile.RestService.ServicioCda.ListarCda();
            return ((FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap)(this)).listarCdaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinancieraMobile.RestService.ServicioCda.ConsultarCda1 FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap.consultarCda(FinancieraMobile.RestService.ServicioCda.ConsultarCda request) {
            return base.Channel.consultarCda(request);
        }
        
        public FinancieraMobile.RestService.ServicioCda.CdaType consultarCda(string cda) {
            FinancieraMobile.RestService.ServicioCda.ConsultarCda inValue = new FinancieraMobile.RestService.ServicioCda.ConsultarCda();
            inValue.Body = new FinancieraMobile.RestService.ServicioCda.ConsultarCdaBody();
            inValue.Body.cda = cda;
            FinancieraMobile.RestService.ServicioCda.ConsultarCda1 retVal = ((FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap)(this)).consultarCda(inValue);
            return retVal.Body.cda;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioCda.ConsultarCda1> FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap.consultarCdaAsync(FinancieraMobile.RestService.ServicioCda.ConsultarCda request) {
            return base.Channel.consultarCdaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FinancieraMobile.RestService.ServicioCda.ConsultarCda1> consultarCdaAsync(string cda) {
            FinancieraMobile.RestService.ServicioCda.ConsultarCda inValue = new FinancieraMobile.RestService.ServicioCda.ConsultarCda();
            inValue.Body = new FinancieraMobile.RestService.ServicioCda.ConsultarCdaBody();
            inValue.Body.cda = cda;
            return ((FinancieraMobile.RestService.ServicioCda.ServicioCdaSoap)(this)).consultarCdaAsync(inValue);
        }
    }
}
