//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5420
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financiera.WebService.Servidor.ServicioCe {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sce.dsd.net/ServicioCe/", ConfigurationName="ServicioCe.ServicioCe")]
    public interface ServicioCe {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de encapsulador (http://sce.dsd.net/TransmitirDigesaRequest) del mensaje TransmitirOrdenRequest no coincide con el valor predeterminado (http://sce.dsd.net/ServicioCe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://sce.dsd.net/ServicioCe/transmitirOrden", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Financiera.WebService.Servidor.ServicioCe.TransmitirOrdenResponse TransmitirOrden(Financiera.WebService.Servidor.ServicioCe.TransmitirOrdenRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de encapsulador (http://sce.dsd.net/TransmitirDigesaRequest) del mensaje TransmitirNroExpedienteRequest no coincide con el valor predeterminado (http://sce.dsd.net/ServicioCe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://sce.dsd.net/ServicioCe/transmitirNroExpediente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Financiera.WebService.Servidor.ServicioCe.TransmitirOrdenResponse TransmitirNroExpediente(Financiera.WebService.Servidor.ServicioCe.TransmitirNroExpedienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de encapsulador (http://sce.dsd.net/TransmitirDigesaRequest) del mensaje TransmitirPagoRequest no coincide con el valor predeterminado (http://sce.dsd.net/ServicioCe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://sce.dsd.net/ServicioCe/transmitirPago", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Financiera.WebService.Servidor.ServicioCe.TransmitirOrdenResponse TransmitirPago(Financiera.WebService.Servidor.ServicioCe.TransmitirPagoRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sce.dsd.net/TransmitirDigesaRequest")]
    public partial class MensajeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string formatoField;
        
        private System.Nullable<long> ordenField;
        
        private System.Nullable<long> suceField;
        
        private string numeroExpedienteField;
        
        private System.Nullable<long> drField;
        
        private string estadoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string formato {
            get {
                return this.formatoField;
            }
            set {
                this.formatoField = value;
                this.RaisePropertyChanged("formato");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
                this.RaisePropertyChanged("orden");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> suce {
            get {
                return this.suceField;
            }
            set {
                this.suceField = value;
                this.RaisePropertyChanged("suce");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string numeroExpediente {
            get {
                return this.numeroExpedienteField;
            }
            set {
                this.numeroExpedienteField = value;
                this.RaisePropertyChanged("numeroExpediente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<long> dr {
            get {
                return this.drField;
            }
            set {
                this.drField = value;
                this.RaisePropertyChanged("dr");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sce.dsd.net/TransmitirDigesaRequest")]
    public partial class UsuarioType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rucField;
        
        private string usuarioSolField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ruc {
            get {
                return this.rucField;
            }
            set {
                this.rucField = value;
                this.RaisePropertyChanged("ruc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string usuarioSol {
            get {
                return this.usuarioSolField;
            }
            set {
                this.usuarioSolField = value;
                this.RaisePropertyChanged("usuarioSol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sce.dsd.net/TransmitirDigesaRequest")]
    public partial class Dgs016ProductoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private string partidaArancelariaField;
        
        private int cantidadField;
        
        private string envaseField;
        
        private string lugarFabricacionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string partidaArancelaria {
            get {
                return this.partidaArancelariaField;
            }
            set {
                this.partidaArancelariaField = value;
                this.RaisePropertyChanged("partidaArancelaria");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string envase {
            get {
                return this.envaseField;
            }
            set {
                this.envaseField = value;
                this.RaisePropertyChanged("envase");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string lugarFabricacion {
            get {
                return this.lugarFabricacionField;
            }
            set {
                this.lugarFabricacionField = value;
                this.RaisePropertyChanged("lugarFabricacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sce.dsd.net/TransmitirDigesaRequest")]
    public partial class Dgs016Type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int tipoProductoField;
        
        private string paisProcedenciaField;
        
        private Dgs016ProductoType[] listaProductoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string paisProcedencia {
            get {
                return this.paisProcedenciaField;
            }
            set {
                this.paisProcedenciaField = value;
                this.RaisePropertyChanged("paisProcedencia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("listaProducto", Order=2)]
        public Dgs016ProductoType[] listaProducto {
            get {
                return this.listaProductoField;
            }
            set {
                this.listaProductoField = value;
                this.RaisePropertyChanged("listaProducto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sce.dsd.net/TransmitirDigesaRequest")]
    public partial class Dgs015ProductoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private string partidaArancelariaField;
        
        private int cantidadField;
        
        private string envaseField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string partidaArancelaria {
            get {
                return this.partidaArancelariaField;
            }
            set {
                this.partidaArancelariaField = value;
                this.RaisePropertyChanged("partidaArancelaria");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string envase {
            get {
                return this.envaseField;
            }
            set {
                this.envaseField = value;
                this.RaisePropertyChanged("envase");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sce.dsd.net/TransmitirDigesaRequest")]
    public partial class Dgs015Type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int tipoProductoField;
        
        private Dgs015ProductoType[] listaProductoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("listaProducto", Order=1)]
        public Dgs015ProductoType[] listaProducto {
            get {
                return this.listaProductoField;
            }
            set {
                this.listaProductoField = value;
                this.RaisePropertyChanged("listaProducto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransmitirOrdenRequest", WrapperNamespace="http://sce.dsd.net/TransmitirDigesaRequest", IsWrapped=true)]
    public partial class TransmitirOrdenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sce.dsd.net/TransmitirDigesaRequest", Order=0)]
        public Financiera.WebService.Servidor.ServicioCe.MensajeType mensaje;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sce.dsd.net/TransmitirDigesaRequest", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("formatoDgs015", typeof(Dgs015Type))]
        [System.Xml.Serialization.XmlElementAttribute("formatoDgs016", typeof(Dgs016Type))]
        public object Item;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sce.dsd.net/TransmitirDigesaRequest", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] adjunto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sce.dsd.net/TransmitirDigesaRequest", Order=3)]
        public Financiera.WebService.Servidor.ServicioCe.UsuarioType usuario;
        
        public TransmitirOrdenRequest() {
        }
        
        public TransmitirOrdenRequest(Financiera.WebService.Servidor.ServicioCe.MensajeType mensaje, object Item, byte[] adjunto, Financiera.WebService.Servidor.ServicioCe.UsuarioType usuario) {
            this.mensaje = mensaje;
            this.Item = Item;
            this.adjunto = adjunto;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransmitirResponse", WrapperNamespace="http://sce.dsd.net/TransmitirResponse", IsWrapped=true)]
    public partial class TransmitirOrdenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sce.dsd.net/TransmitirResponse", Order=0)]
        public string codigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sce.dsd.net/TransmitirResponse", Order=1)]
        public string texto;
        
        public TransmitirOrdenResponse() {
        }
        
        public TransmitirOrdenResponse(string codigo, string texto) {
            this.codigo = codigo;
            this.texto = texto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransmitirNroExpedienteRequest", WrapperNamespace="http://sce.dsd.net/TransmitirDigesaRequest", IsWrapped=true)]
    public partial class TransmitirNroExpedienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sce.dsd.net/TransmitirDigesaRequest", Order=0)]
        public Financiera.WebService.Servidor.ServicioCe.MensajeType mensaje;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sce.dsd.net/TransmitirDigesaRequest", Order=1)]
        public Financiera.WebService.Servidor.ServicioCe.UsuarioType usuario;
        
        public TransmitirNroExpedienteRequest() {
        }
        
        public TransmitirNroExpedienteRequest(Financiera.WebService.Servidor.ServicioCe.MensajeType mensaje, Financiera.WebService.Servidor.ServicioCe.UsuarioType usuario) {
            this.mensaje = mensaje;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransmitirPagoRequest", WrapperNamespace="http://sce.dsd.net/TransmitirDigesaRequest", IsWrapped=true)]
    public partial class TransmitirPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sce.dsd.net/TransmitirDigesaRequest", Order=0)]
        public string cda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sce.dsd.net/TransmitirDigesaRequest", Order=1)]
        public double monto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sce.dsd.net/TransmitirDigesaRequest", Order=2)]
        public System.DateTime fechaPago;
        
        public TransmitirPagoRequest() {
        }
        
        public TransmitirPagoRequest(string cda, double monto, System.DateTime fechaPago) {
            this.cda = cda;
            this.monto = monto;
            this.fechaPago = fechaPago;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServicioCeChannel : Financiera.WebService.Servidor.ServicioCe.ServicioCe, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServicioCeClient : System.ServiceModel.ClientBase<Financiera.WebService.Servidor.ServicioCe.ServicioCe>, Financiera.WebService.Servidor.ServicioCe.ServicioCe {
        
        public ServicioCeClient() {
        }
        
        public ServicioCeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Financiera.WebService.Servidor.ServicioCe.TransmitirOrdenResponse Financiera.WebService.Servidor.ServicioCe.ServicioCe.TransmitirOrden(Financiera.WebService.Servidor.ServicioCe.TransmitirOrdenRequest request) {
            return base.Channel.TransmitirOrden(request);
        }
        
        public string TransmitirOrden(Financiera.WebService.Servidor.ServicioCe.MensajeType mensaje, object Item, byte[] adjunto, Financiera.WebService.Servidor.ServicioCe.UsuarioType usuario, out string texto) {
            Financiera.WebService.Servidor.ServicioCe.TransmitirOrdenRequest inValue = new Financiera.WebService.Servidor.ServicioCe.TransmitirOrdenRequest();
            inValue.mensaje = mensaje;
            inValue.Item = Item;
            inValue.adjunto = adjunto;
            inValue.usuario = usuario;
            Financiera.WebService.Servidor.ServicioCe.TransmitirOrdenResponse retVal = ((Financiera.WebService.Servidor.ServicioCe.ServicioCe)(this)).TransmitirOrden(inValue);
            texto = retVal.texto;
            return retVal.codigo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Financiera.WebService.Servidor.ServicioCe.TransmitirOrdenResponse Financiera.WebService.Servidor.ServicioCe.ServicioCe.TransmitirNroExpediente(Financiera.WebService.Servidor.ServicioCe.TransmitirNroExpedienteRequest request) {
            return base.Channel.TransmitirNroExpediente(request);
        }
        
        public string TransmitirNroExpediente(Financiera.WebService.Servidor.ServicioCe.MensajeType mensaje, Financiera.WebService.Servidor.ServicioCe.UsuarioType usuario, out string texto) {
            Financiera.WebService.Servidor.ServicioCe.TransmitirNroExpedienteRequest inValue = new Financiera.WebService.Servidor.ServicioCe.TransmitirNroExpedienteRequest();
            inValue.mensaje = mensaje;
            inValue.usuario = usuario;
            Financiera.WebService.Servidor.ServicioCe.TransmitirOrdenResponse retVal = ((Financiera.WebService.Servidor.ServicioCe.ServicioCe)(this)).TransmitirNroExpediente(inValue);
            texto = retVal.texto;
            return retVal.codigo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Financiera.WebService.Servidor.ServicioCe.TransmitirOrdenResponse Financiera.WebService.Servidor.ServicioCe.ServicioCe.TransmitirPago(Financiera.WebService.Servidor.ServicioCe.TransmitirPagoRequest request) {
            return base.Channel.TransmitirPago(request);
        }
        
        public string TransmitirPago(string cda, double monto, System.DateTime fechaPago, out string texto) {
            Financiera.WebService.Servidor.ServicioCe.TransmitirPagoRequest inValue = new Financiera.WebService.Servidor.ServicioCe.TransmitirPagoRequest();
            inValue.cda = cda;
            inValue.monto = monto;
            inValue.fechaPago = fechaPago;
            Financiera.WebService.Servidor.ServicioCe.TransmitirOrdenResponse retVal = ((Financiera.WebService.Servidor.ServicioCe.ServicioCe)(this)).TransmitirPago(inValue);
            texto = retVal.texto;
            return retVal.codigo;
        }
    }
}
